import {TestBed} from '@angular/core/testing';
import {provideRouter,ActivatedRoute,convertToParamMap} from '@angular/router';
import {signal} from '@angular/core';import {of,Subject,throwError} from 'rxjs';
import {SiteComponent} from './site.component';import {SitePublicoComponent} from './site-publico.component';
import {SiteApiService,EstadoSite,DadosSite} from './site-api.service';
import {SessaoAtual} from '../../core/layout/sessao-atual';import {DialogoService} from '../../shared/services/dialogo.service';
describe('Página pública: revisão e publicação',()=>{
 let api:jasmine.SpyObj<SiteApiService>,dialogo:jasmine.SpyObj<DialogoService>;const permissoes=signal(['SITE_EDITAR','SITE_PUBLICAR']);
 const dados:DadosSite={titulo:'Paróquia',apresentacao:'Texto público',endereco:null,horarios:null,contato:null,blocos:[]};const estado:EstadoSite={versao:4,slug:'paroquia',rascunho:dados,publicado:null,publicadoEm:null};
 beforeEach(()=>{api=jasmine.createSpyObj('site',['consultar','salvar','publicar','despublicar','publico']);api.consultar.and.returnValue(of(estado));api.publicar.and.returnValue(of({...estado,versao:5,publicado:dados}));dialogo=jasmine.createSpyObj('dialogo',['confirmar']);dialogo.confirmar.and.resolveTo(true);permissoes.set(['SITE_EDITAR','SITE_PUBLICAR']);TestBed.configureTestingModule({imports:[SiteComponent],providers:[provideRouter([]),{provide:SiteApiService,useValue:api},{provide:SessaoAtual,useValue:{permissoes}},{provide:DialogoService,useValue:dialogo}]});});
 it('editar preserva o snapshot e não publica automaticamente',()=>{const f=TestBed.createComponent(SiteComponent);f.detectChanges();f.componentInstance.dados.titulo='Mudança';f.componentInstance.alterado.set(true);expect(estado.rascunho.titulo).toBe('Paróquia');expect(f.componentInstance.hasPendingChanges()).toBeTrue();expect(api.publicar).not.toHaveBeenCalled();});
 it('bloqueia publicação de alterações não salvas',async()=>{const f=TestBed.createComponent(SiteComponent);f.detectChanges();f.componentInstance.alterado.set(true);await f.componentInstance.publicar();expect(dialogo.confirmar).not.toHaveBeenCalled();expect(api.publicar).not.toHaveBeenCalled();});
 it('publica apenas após confirmação explícita e envia a versão',async()=>{const f=TestBed.createComponent(SiteComponent);f.detectChanges();await f.componentInstance.publicar();expect(dialogo.confirmar).toHaveBeenCalled();expect(api.publicar).toHaveBeenCalledOnceWith(4);expect(f.componentInstance.estado()?.versao).toBe(5);});
 it('cancelar não publica',async()=>{dialogo.confirmar.and.resolveTo(false);const f=TestBed.createComponent(SiteComponent);f.detectChanges();await f.componentInstance.publicar();expect(api.publicar).not.toHaveBeenCalled();expect(f.componentInstance.ocupado()).toBeFalse();});
 it('leitor não publica nem adiciona blocos',async()=>{permissoes.set([]);const f=TestBed.createComponent(SiteComponent);f.detectChanges();f.componentInstance.adicionarBloco();await f.componentInstance.publicar();expect(api.publicar).not.toHaveBeenCalled();expect(f.componentInstance.dados.blocos).toEqual([]);});
 it('conflito não faz repetição automática',async()=>{api.publicar.and.returnValue(throwError(()=>({status:409,error:{message:'Atualize'}})));const f=TestBed.createComponent(SiteComponent);f.detectChanges();await f.componentInstance.publicar();expect(api.publicar).toHaveBeenCalledTimes(1);expect(f.componentInstance.estado()?.publicado).toBeNull();expect(f.componentInstance.erro()).toBeTruthy();});
 it('navegar durante confirmação impede escrita',async()=>{let responder!:(v:boolean)=>void;dialogo.confirmar.and.returnValue(new Promise(r=>responder=r));const f=TestBed.createComponent(SiteComponent);f.detectChanges();const pedido=f.componentInstance.publicar();f.destroy();responder(true);await pedido;expect(api.publicar).not.toHaveBeenCalled();});
});
describe('Página anônima: isolamento e texto seguro',()=>{
 const params=new Subject<ReturnType<typeof convertToParamMap>>();let api:jasmine.SpyObj<SiteApiService>;const dados:DadosSite={titulo:'<script>alert(1)</script>',apresentacao:'Público',endereco:null,horarios:null,contato:null,blocos:[]};
 beforeEach(()=>{api=jasmine.createSpyObj('site',['publico']);api.publico.and.returnValue(of(dados));TestBed.configureTestingModule({imports:[SitePublicoComponent],providers:[{provide:SiteApiService,useValue:api},{provide:ActivatedRoute,useValue:{paramMap:params}}]});});
 it('renderiza textos sem executar HTML',()=>{const f=TestBed.createComponent(SitePublicoComponent);f.detectChanges();params.next(convertToParamMap({slug:'a'}));f.detectChanges();expect(f.nativeElement.querySelector('script')).toBeNull();expect(f.nativeElement.textContent).toContain('<script>');f.destroy();});
 it('trocar slug cancela a resposta antiga e limpa o conteúdo',()=>{const antiga=new Subject<DadosSite>();api.publico.and.returnValue(antiga);const f=TestBed.createComponent(SitePublicoComponent);f.detectChanges();params.next(convertToParamMap({slug:'a'}));api.publico.and.returnValue(throwError(()=>new Error('404')));params.next(convertToParamMap({slug:'b'}));antiga.next(dados);expect(antiga.observed).toBeFalse();expect(f.componentInstance.dados()).toBeNull();expect(f.componentInstance.erro()).toBeTrue();f.destroy();});
});
