import { Component,ChangeDetectionStrategy,OnInit,OnDestroy,inject,signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Subscription } from 'rxjs';
import { SiteApiService,DadosSite } from './site-api.service';
@Component({selector:'app-site-publico',changeDetection:ChangeDetectionStrategy.OnPush,template:`<main class="parish min-h-screen p-5"><div class="mx-auto max-w-4xl space-y-5">@if(carregando()){<p role="status">Consultando a página…</p>}@if(erro()){<p class="card p-5" role="alert">Página indisponível. Confira o endereço ou tente novamente mais tarde.</p>}@if(dados();as d){<header class="card p-6 space-y-3"><h1 class="text-3xl font-bold">{{d.titulo}}</h1><p class="whitespace-pre-wrap">{{d.apresentacao}}</p></header>@if(d.endereco||d.horarios||d.contato){<section class="card p-6 space-y-3"><h2 class="secao-titulo">Informações da paróquia</h2>@if(d.endereco){<p>{{d.endereco}}</p>}@if(d.horarios){<h3 class="font-bold">Horários</h3><p class="whitespace-pre-wrap">{{d.horarios}}</p>}@if(d.contato){<h3 class="font-bold">Contato público</h3><p>{{d.contato}}</p>}</section>}@for(b of d.blocos;track $index){<article class="card p-6 space-y-3"><span class="badge bg-slate-100 text-slate-600">{{b.tipo==='EVENTO'?'Evento':'Aviso'}}</span><h2 class="text-xl font-bold">{{b.titulo}}</h2>@if(b.quando){<p>{{b.quando}}</p>}@if(b.local){<p>{{b.local}}</p>}<p class="whitespace-pre-wrap">{{b.texto}}</p></article>}}<footer class="text-sm text-slate-500">Informações publicadas pela paróquia.</footer></div></main>`})
export class SitePublicoComponent implements OnInit,OnDestroy{
 private readonly api=inject(SiteApiService);private readonly route=inject(ActivatedRoute);private params?:Subscription;private leitura?:Subscription;readonly dados=signal<DadosSite|null>(null);readonly erro=signal(false);readonly carregando=signal(false);
 ngOnInit(){this.params=this.route.paramMap.subscribe(p=>{this.leitura?.unsubscribe();this.dados.set(null);this.erro.set(false);this.carregando.set(true);this.leitura=this.api.publico(p.get('slug')||'').subscribe({next:d=>{this.dados.set(d);this.carregando.set(false);},error:()=>{this.erro.set(true);this.carregando.set(false);}});});}
 ngOnDestroy(){this.params?.unsubscribe();this.leitura?.unsubscribe();}
}
