import { Component,ChangeDetectionStrategy,OnInit,OnDestroy,inject,signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule,NgForm } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { SiteApiService,EstadoSite,DadosSite } from './site-api.service';
import { SessaoAtual } from '../../core/layout/sessao-atual';
import { mensagemApi } from '../../core/api/api-error';
import { DialogoService } from '../../shared/services/dialogo.service';
import { CabecalhoPaginaComponent } from '../../shared/components/cabecalho-pagina/cabecalho-pagina.component';
import { RodapeFormComponent } from '../../shared/components/rodape-form/rodape-form.component';
@Component({selector:'app-site-editor',imports:[CommonModule,FormsModule,RouterLink,CabecalhoPaginaComponent,RodapeFormComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<div class="space-y-5"><app-cabecalho-pagina titulo="Página pública da paróquia" subtitulo="Revise os textos e contatos. Só o conteúdo publicado ficará visível sem login."><div acoes><button type="button" class="btn-secondary" [disabled]="ocupado()||alterado()" (click)="carregar()">Atualizar</button></div></app-cabecalho-pagina>@if(erro()){<p role="alert" class="card p-4 text-red-700">{{erro()}}</p>}@if(aviso()){<p role="status" class="card p-4 text-emerald-700">{{aviso()}}</p>}
@if(estado();as e){<section class="card p-5 space-y-3"><h2 class="secao-titulo">Publicação</h2><span class="badge" [class]="e.publicado?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'">{{e.publicado?'Página publicada':'Página fora do ar'}}</span><p>O rascunho é independente da versão pública. Nomes de voluntários, escala e fichas internas não são importados automaticamente.</p>@if(e.publicado){<a class="btn-secondary" [routerLink]="['/p',e.slug]" target="_blank" rel="noopener">Abrir página publicada</a>}@if(pode('SITE_PUBLICAR')){<button type="button" class="btn-primary" [disabled]="ocupado()||alterado()" (click)="publicar()">Publicar rascunho salvo</button>@if(e.publicado){<button type="button" class="btn-danger" [disabled]="ocupado()" (click)="despublicar()">Retirar página do ar</button>}}@if(alterado()){<p class="text-amber-700">Salve ou descarte as alterações antes de publicar.</p>}</section>
<form #form="ngForm" (ngSubmit)="salvar(form)"><section class="card p-5 space-y-4"><h2 class="secao-titulo">Rascunho</h2><fieldset [disabled]="ocupado()||!pode('SITE_EDITAR')" class="space-y-3"><label class="label" for="site-titulo">Título público</label><input id="site-titulo" name="titulo" class="field w-full" required maxlength="160" [(ngModel)]="dados.titulo" (ngModelChange)="alterado.set(true)"><label class="label" for="site-apresentacao">Apresentação</label><textarea id="site-apresentacao" name="apresentacao" class="field w-full" required maxlength="4000" rows="4" [(ngModel)]="dados.apresentacao" (ngModelChange)="alterado.set(true)"></textarea><label class="label" for="site-endereco">Endereço que pode ser público</label><input id="site-endereco" name="endereco" class="field w-full" maxlength="500" [(ngModel)]="dados.endereco" (ngModelChange)="alterado.set(true)"><label class="label" for="site-horarios">Horários públicos</label><textarea id="site-horarios" name="horarios" class="field w-full" maxlength="1000" [(ngModel)]="dados.horarios" (ngModelChange)="alterado.set(true)"></textarea><label class="label" for="site-contato">Contato público da paróquia</label><input id="site-contato" name="contato" class="field w-full" maxlength="200" [(ngModel)]="dados.contato" (ngModelChange)="alterado.set(true)"><p class="text-sm text-slate-500">Não inclua contatos pessoais sem autorização. Todo conteúdo é texto; não há execução de HTML.</p>
@for(b of dados.blocos;track $index;let i=$index){<section class="border rounded-xl p-4 space-y-2"><h3>Bloco {{i+1}}</h3><label class="label" [for]="'bloco-tipo-'+i">Tipo</label><select [id]="'bloco-tipo-'+i" [name]="'tipo'+i" class="field" [(ngModel)]="b.tipo" (ngModelChange)="alterado.set(true)"><option value="AVISO">Aviso público</option><option value="EVENTO">Evento público</option></select><label class="label" [for]="'bloco-titulo-'+i">Título</label><input [id]="'bloco-titulo-'+i" [name]="'titulo'+i" class="field w-full" required maxlength="160" [(ngModel)]="b.titulo" (ngModelChange)="alterado.set(true)"><label class="label" [for]="'bloco-texto-'+i">Texto público</label><textarea [id]="'bloco-texto-'+i" [name]="'texto'+i" class="field w-full" required maxlength="4000" [(ngModel)]="b.texto" (ngModelChange)="alterado.set(true)"></textarea><label class="label" [for]="'bloco-quando-'+i">Quando (texto)</label><input [id]="'bloco-quando-'+i" [name]="'quando'+i" class="field" maxlength="100" [(ngModel)]="b.quando" (ngModelChange)="alterado.set(true)"><label class="label" [for]="'bloco-local-'+i">Local público</label><input [id]="'bloco-local-'+i" [name]="'local'+i" class="field" maxlength="200" [(ngModel)]="b.local" (ngModelChange)="alterado.set(true)"><button type="button" class="btn-danger" (click)="removerBloco(i)">Remover bloco</button></section>}
<button type="button" class="btn-secondary" [disabled]="dados.blocos.length>=30" (click)="adicionarBloco()">Adicionar aviso ou evento</button></fieldset></section>@if(pode('SITE_EDITAR')){<app-rodape-form [carregando]="ocupado()" (cancelar)="descartar()"/>}</form>
<section class="card p-5 space-y-3"><h2 class="secao-titulo">Prévia do rascunho</h2><h3>{{dados.titulo}}</h3><p class="whitespace-pre-wrap">{{dados.apresentacao}}</p><p>{{dados.endereco}}</p><p class="whitespace-pre-wrap">{{dados.horarios}}</p><p>{{dados.contato}}</p>@for(b of dados.blocos;track $index){<h3>{{b.titulo}}</h3><p>{{b.quando}} {{b.local}}</p><p class="whitespace-pre-wrap">{{b.texto}}</p>}</section>}
</div>`})
export class SiteComponent implements OnInit,OnDestroy{
 private readonly api=inject(SiteApiService);private readonly sessao=inject(SessaoAtual);private readonly dialogo=inject(DialogoService);private leitura?:Subscription;private escrita?:Subscription;private destruido=false;
 readonly estado=signal<EstadoSite|null>(null);readonly erro=signal('');readonly aviso=signal('');readonly ocupado=signal(false);readonly alterado=signal(false);dados:DadosSite={titulo:'',apresentacao:'',endereco:null,horarios:null,contato:null,blocos:[]};
 ngOnInit(){this.carregar();}pode(c:string){return this.sessao.permissoes().includes(c);}hasPendingChanges(){return this.alterado();}
 private aplicar(e:EstadoSite){this.estado.set(e);this.dados={...e.rascunho,blocos:e.rascunho.blocos.map(b=>({...b}))};this.alterado.set(false);}
 carregar(){if(this.ocupado()||this.destruido)return;this.leitura?.unsubscribe();this.estado.set(null);this.erro.set('');this.ocupado.set(true);this.leitura=this.api.consultar().subscribe({next:e=>{this.aplicar(e);this.ocupado.set(false);},error:e=>{this.ocupado.set(false);this.erro.set(mensagemApi(e,'Página indisponível.'));}});}
 adicionarBloco(){if(this.ocupado()||!this.pode('SITE_EDITAR')||this.dados.blocos.length>=30)return;this.dados.blocos.push({tipo:'AVISO',titulo:'',texto:'',quando:null,local:null});this.alterado.set(true);}
 async removerBloco(i:number){if(this.ocupado()||!this.pode('SITE_EDITAR'))return;const bloco=this.dados.blocos[i];if(!bloco)return;if(await this.dialogo.confirmar({mensagem:'Remover este bloco do rascunho?',confirmar:'Remover',perigo:true})&&!this.destruido){const atual=this.dados.blocos.indexOf(bloco);if(atual>=0){this.dados.blocos.splice(atual,1);this.alterado.set(true);}}}
 salvar(f:NgForm){const e=this.estado();if(!e||this.ocupado()||!this.pode('SITE_EDITAR'))return;if(f.invalid){f.control.markAllAsTouched();return;}this.ocupado.set(true);this.erro.set('');this.escrita=this.api.salvar(e.versao,{...this.dados,blocos:this.dados.blocos.map(b=>({...b}))}).subscribe({next:r=>{this.aplicar(r);this.ocupado.set(false);this.aviso.set('Rascunho salvo. A publicação é uma ação separada.');},error:erro=>{this.ocupado.set(false);this.erro.set(mensagemApi(erro,'Não foi possível salvar. Atualize antes de tentar novamente.'));}});}
 async publicar(){const e=this.estado();if(!e||this.ocupado()||this.alterado()||!this.pode('SITE_PUBLICAR'))return;this.ocupado.set(true);try{if(!await this.dialogo.confirmar({mensagem:'Publicar os textos, horários, endereço e contatos deste rascunho para qualquer pessoa, sem login? Revise se todo conteúdo pode ser público.',confirmar:'Publicar'})||this.destruido){this.ocupado.set(false);return;}this.escrita=this.api.publicar(e.versao).subscribe({next:r=>{this.aplicar(r);this.ocupado.set(false);this.aviso.set('Página publicada.');},error:erro=>{this.ocupado.set(false);this.erro.set(mensagemApi(erro,'Não foi possível publicar. Atualize.'));}});}catch{this.ocupado.set(false);}}
 async despublicar(){const e=this.estado();if(!e||!e.publicado||this.ocupado()||!this.pode('SITE_PUBLICAR'))return;this.ocupado.set(true);try{if(!await this.dialogo.confirmar({mensagem:'Retirar a página pública do ar? O rascunho será preservado.',confirmar:'Retirar do ar',perigo:true})||this.destruido){this.ocupado.set(false);return;}this.escrita=this.api.despublicar(e.versao).subscribe({next:r=>{this.estado.set(r);this.ocupado.set(false);this.aviso.set('Página retirada do ar.');},error:erro=>{this.ocupado.set(false);this.erro.set(mensagemApi(erro,'Não foi possível retirar a página. Atualize.'));}});}catch{this.ocupado.set(false);}}
 async descartar(){if(this.ocupado())return;if(!this.alterado()||await this.dialogo.confirmar({mensagem:'Descartar as alterações do rascunho?',confirmar:'Descartar',perigo:true})){if(this.destruido)return;this.alterado.set(false);this.carregar();}}
 ngOnDestroy(){this.destruido=true;this.leitura?.unsubscribe();this.escrita?.unsubscribe();}
}
