import {BarraFiltrosComponent} from '../../shared/components/barra-filtros/barra-filtros.component';
import {Component,ChangeDetectionStrategy,OnInit,OnDestroy,inject,signal} from '@angular/core';import {FormsModule} from '@angular/forms';import {HttpClient} from '@angular/common/http';import {ActivatedRoute,RouterLink} from '@angular/router';import {Subscription} from 'rxjs';
import {environment} from '../../../environments/environment';import {mensagemApi} from '../../core/api/api-error';import {DialogoService} from '../../shared/services/dialogo.service';import {SessaoAtual} from '../../core/layout/sessao-atual';import {CabecalhoPaginaComponent} from '../../shared/components/cabecalho-pagina/cabecalho-pagina.component';
interface Autorizacao{pessoaId:string;nome:string;consulta:boolean;resposta:boolean;versao:number;}
@Component({selector:'app-autorizacoes-dependentes',imports:[BarraFiltrosComponent,FormsModule,RouterLink,CabecalhoPaginaComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`<div class="space-y-5"><app-cabecalho-pagina titulo="Acesso aos dependentes" subtitulo="Autorize somente após conferir a identidade e a relação de responsabilidade." />
<a routerLink="/pessoas" class="btn-secondary">Voltar às pessoas</a>@if(erro()){<p role="alert" class="text-red-700">{{erro()}}</p>}
<app-barra-filtros [semBusca]="true" [temFiltros]="false" (buscar)="carregar()" /><div class="card tabela-rolagem"><table class="tabela"><thead><tr><th>Dependente</th><th>Consultar</th><th>Responder</th><th>Ação</th></tr></thead><tbody>@for(d of itens();track d.pessoaId){<tr><td>{{d.nome}}</td><td><input type="checkbox" [(ngModel)]="d.consulta" [disabled]="!pode()||ocupado()" [attr.aria-label]="'Permitir consulta de '+d.nome" (ngModelChange)="!d.consulta && (d.resposta=false)"></td><td><input type="checkbox" [(ngModel)]="d.resposta" [disabled]="!pode()||!d.consulta||ocupado()" [attr.aria-label]="'Permitir resposta por '+d.nome"></td><td>@if(pode()){<button class="btn-primary" [disabled]="ocupado()" (click)="salvar(d)">Salvar autorização</button>}</td></tr>}</tbody></table></div>
@if(!itens().length){<p>Nenhum dependente vinculado nesta página.</p>}<div class="flex gap-3"><button class="btn-secondary" [disabled]="pagina===0||ocupado()" (click)="paginar(-1)">Anterior</button><button class="btn-secondary" [disabled]="itens().length<30||ocupado()" (click)="paginar(1)">Próxima</button></div></div>`})
export class AutorizacoesDependentesComponent implements OnInit,OnDestroy {
 private http=inject(HttpClient);private route=inject(ActivatedRoute);private sessao=inject(SessaoAtual);private dialogo=inject(DialogoService);private leitura?:Subscription;private escrita?:Subscription;private rota?:Subscription;private destruido=false;responsavel='';pagina=0;itens=signal<Autorizacao[]>([]);erro=signal('');ocupado=signal(false);
 ngOnInit(){this.rota=this.route.paramMap.subscribe(p=>{this.responsavel=p.get('id')||'';this.pagina=0;this.carregar();});}pode(){return this.sessao.permissoes().includes('PESSOA_ALTERAR');}
 carregar(){if(this.ocupado())return;this.leitura?.unsubscribe();this.itens.set([]);this.leitura=this.http.get<Autorizacao[]>(`${environment.apiUrl}/pessoas/${this.responsavel}/acessos-dependentes`,{params:{pagina:this.pagina}}).subscribe({next:d=>this.itens.set(d),error:e=>this.erro.set(mensagemApi(e,'Não foi possível conferir relações.'))});}
 paginar(delta:number){if(this.ocupado())return;this.pagina+=delta;this.carregar();}
 async salvar(d:Autorizacao){if(!this.pode()||this.ocupado())return;const responsavel=this.responsavel;const body={consulta:d.consulta,resposta:d.resposta,versao:d.versao};if(!await this.dialogo.confirmar({mensagem:`Salvar a autorização para ${d.nome}? O vínculo cadastral sozinho não concede acesso.`,confirmar:'Salvar autorização'}))return;if(this.destruido||this.ocupado()||responsavel!==this.responsavel)return;this.ocupado.set(true);this.escrita=this.http.put(`${environment.apiUrl}/pessoas/${responsavel}/acessos-dependentes/${d.pessoaId}`,body).subscribe({next:()=>{this.ocupado.set(false);this.carregar();},error:e=>{this.ocupado.set(false);this.carregar();this.erro.set(mensagemApi(e,'Não foi possível salvar autorização.'));}});}
 ngOnDestroy(){this.destruido=true;this.rota?.unsubscribe();this.leitura?.unsubscribe();this.escrita?.unsubscribe();}
}
