import {TestBed} from '@angular/core/testing';import {signal} from '@angular/core';import {of,Subject} from 'rxjs';
import {DependentesComponent} from './dependentes.component';import {VoluntarioApiService,Portal,Compromisso} from './voluntario-api.service';import {SessaoAtual} from '../../core/layout/sessao-atual';import {DialogoService} from '../../shared/services/dialogo.service';
describe('Acesso dos responsáveis',()=>{
 let api:jasmine.SpyObj<VoluntarioApiService>,dialogo:jasmine.SpyObj<DialogoService>;
 const filho={pessoaId:'filho',nome:'Dependente',podeResponder:true};const c:Compromisso={id:'escala-v',tipo:'ESCALA',titulo:'Missa',inicio:'2099-10-02T19:00:00',termino:'2099-10-02T20:00:00',local:null,funcao:'CRUZ',vagaId:'v',resposta:'PENDENTE',versao:3,respondidoEm:null,prazoResposta:'2099-10-02T22:00:00Z'};
 beforeEach(()=>{api=jasmine.createSpyObj('api',['dependentes','consultarDependente','responderDependente']);api.dependentes.and.returnValue(of([filho]));api.consultarDependente.and.returnValue(of({vinculado:true,compromissos:[c]}));api.responderDependente.and.returnValue(of({} as any));dialogo=jasmine.createSpyObj('dialogo',['confirmar']);dialogo.confirmar.and.resolveTo(true);TestBed.configureTestingModule({imports:[DependentesComponent],providers:[{provide:VoluntarioApiService,useValue:api},{provide:SessaoAtual,useValue:{permissoes:signal(['PORTAL_DEPENDENTES','PORTAL_RESPONDER'])}},{provide:DialogoService,useValue:dialogo}]});});
 it('autorização somente para consultar não permite resposta',async()=>{const f=TestBed.createComponent(DependentesComponent);f.detectChanges();f.componentInstance.selecionar({...filho,podeResponder:false});await f.componentInstance.responder(c,'CONFIRMADA');expect(api.responderDependente).not.toHaveBeenCalled();});
 it('responde pelo dependente selecionado com a versão consultada',async()=>{const f=TestBed.createComponent(DependentesComponent);f.detectChanges();f.componentInstance.selecionar(filho);await f.componentInstance.responder(c,'RECUSADA');expect(api.responderDependente).toHaveBeenCalledOnceWith('filho','v','RECUSADA',3);});
 it('troca de página cancela compromissos do dependente anterior',()=>{const antigo=new Subject<Portal>();api.consultarDependente.and.returnValue(antigo);const f=TestBed.createComponent(DependentesComponent);f.detectChanges();f.componentInstance.selecionar(filho);f.componentInstance.paginar(1);antigo.next({vinculado:true,compromissos:[c]});expect(f.componentInstance.dados()).toBeNull();expect(f.componentInstance.selecionado()).toBeNull();});
 it('confirmação atrasada não escreve pelo dependente anterior',async()=>{let confirmar!:(v:boolean)=>void;dialogo.confirmar.and.returnValue(new Promise(r=>confirmar=r));const f=TestBed.createComponent(DependentesComponent);f.detectChanges();f.componentInstance.selecionar(filho);const acao=f.componentInstance.responder(c,'CONFIRMADA');f.componentInstance.selecionar({...filho,pessoaId:'outro'});confirmar(true);await acao;expect(api.responderDependente).not.toHaveBeenCalled();});
 it('saída da tela cancela confirmação e prazo vencido bloqueia',async()=>{const f=TestBed.createComponent(DependentesComponent);f.detectChanges();f.componentInstance.selecionar(filho);await f.componentInstance.responder({...c,prazoResposta:'2000-01-01T00:00:00Z'},'CONFIRMADA');expect(api.responderDependente).not.toHaveBeenCalled();let confirmar!:(v:boolean)=>void;dialogo.confirmar.and.returnValue(new Promise(r=>confirmar=r));const acao=f.componentInstance.responder(c,'CONFIRMADA');f.destroy();confirmar(true);await acao;expect(api.responderDependente).not.toHaveBeenCalled();});
});
