import { By } from '@angular/platform-browser';
import { NgForm } from '@angular/forms';
import { TestBed } from '@angular/core/testing';
import { signal } from '@angular/core';
import { ActivatedRoute,provideRouter } from '@angular/router';
import { of,Subject,throwError } from 'rxjs';
import { TrocasComponent } from './trocas.component';
import { TrocasApiService,Troca } from './trocas-api.service';
import { VoluntarioApiService } from './voluntario-api.service';
import { SessaoAtual } from '../../core/layout/sessao-atual';
import { DialogoService } from '../../shared/services/dialogo.service';
describe('Trocas pessoais e da coordenação',()=>{
 let api:jasmine.SpyObj<TrocasApiService>;let portal:jasmine.SpyObj<VoluntarioApiService>;let dialogo:jasmine.SpyObj<DialogoService>;let escala:string|null;const permissoes=signal<string[]>([]);
 const pedido:Troca={id:'p',vagaId:'v',celebracao:'Missa',inicio:'2099-10-02T21:00:00',funcao:'MISSAL',situacao:'AGUARDANDO_ACEITE',versao:3,criadaEm:'2026-10-02T00:00:00Z',atualizadaEm:'2026-10-02T00:00:00Z',solicitanteNome:'A',substitutoNome:'B',solicitante:false,substituto:true,vigente:true};
 beforeEach(()=>{escala=null;permissoes.set(['PORTAL_VOLUNTARIO','PORTAL_TROCAR']);api=jasmine.createSpyObj('api',['minhas','substitutos','solicitar','responder','cancelar','coordenacao','decidir']);api.minhas.and.returnValue(of({itens:[pedido],total:1,pagina:0,tamanho:30}));api.coordenacao.and.returnValue(of({itens:[pedido],total:1,pagina:0,tamanho:30}));api.substitutos.and.returnValue(of([{id:'b',nome:'B'}]));api.responder.and.returnValue(of({...pedido,situacao:'ACEITA'}));api.decidir.and.returnValue(of({...pedido,situacao:'APROVADA'}));api.cancelar.and.returnValue(of({...pedido,situacao:'CANCELADA'}));portal=jasmine.createSpyObj('portal',['consultar']);portal.consultar.and.returnValue(of({vinculado:true,compromissos:[]}));dialogo=jasmine.createSpyObj('dialogo',['confirmar']);dialogo.confirmar.and.resolveTo(true);TestBed.configureTestingModule({imports:[TrocasComponent],providers:[provideRouter([]),{provide:TrocasApiService,useValue:api},{provide:VoluntarioApiService,useValue:portal},{provide:SessaoAtual,useValue:{permissoes}},{provide:DialogoService,useValue:dialogo},{provide:ActivatedRoute,useValue:{snapshot:{paramMap:{get:()=>escala}}}}]});});
 it('aceita com versão e recarrega',async()=>{const f=TestBed.createComponent(TrocasComponent);f.detectChanges();await f.componentInstance.responder(pedido,true);expect(api.responder).toHaveBeenCalledOnceWith('p',true,3);expect(api.minhas).toHaveBeenCalledTimes(2);});
 it('solicitante não aceita pelo substituto',async()=>{const f=TestBed.createComponent(TrocasComponent);await f.componentInstance.responder({...pedido,substituto:false,solicitante:true},true);expect(api.responder).not.toHaveBeenCalled();});
 it('perfil de consulta não pode aceitar',async()=>{permissoes.set(['PORTAL_VOLUNTARIO']);const f=TestBed.createComponent(TrocasComponent);f.detectChanges();await f.componentInstance.responder(pedido,true);expect(api.responder).not.toHaveBeenCalled();});
 it('não aprova antes do aceite',async()=>{escala='s';permissoes.set(['VAGA_TROCA_LER','VAGA_TROCA_DECIDIR']);const f=TestBed.createComponent(TrocasComponent);f.detectChanges();await f.componentInstance.decidir(pedido,true);expect(api.decidir).not.toHaveBeenCalled();expect(portal.consultar).not.toHaveBeenCalled();});
 it('aprova depois do aceite pela coordenação',async()=>{escala='s';permissoes.set(['VAGA_TROCA_LER','VAGA_TROCA_DECIDIR']);const f=TestBed.createComponent(TrocasComponent);f.detectChanges();await f.componentInstance.decidir({...pedido,situacao:'ACEITA'},true);expect(api.decidir).toHaveBeenCalledOnceWith('p',true,3);});
 it('conflito recarrega sem repetir escrita',async()=>{api.responder.and.returnValue(throwError(()=>({status:409})));const f=TestBed.createComponent(TrocasComponent);f.detectChanges();await f.componentInstance.responder(pedido,true);expect(api.responder).toHaveBeenCalledTimes(1);expect(api.minhas).toHaveBeenCalledTimes(2);expect(f.componentInstance.erro()).toBeTruthy();});
 it('leitura antiga não substitui dados novos',()=>{const antigo=new Subject<any>();api.minhas.and.returnValue(antigo);const f=TestBed.createComponent(TrocasComponent);f.detectChanges();api.minhas.and.returnValue(of({itens:[],total:0,pagina:0,tamanho:30}));f.componentInstance.buscar();antigo.next({itens:[pedido],total:1});antigo.complete();expect(f.componentInstance.pedidos()).toEqual([]);});
 it('não consulta diretório com termo curto',async()=>{const f=TestBed.createComponent(TrocasComponent);expect(await f.componentInstance.buscarSubstitutos('A')).toEqual([]);expect(api.substitutos).not.toHaveBeenCalled();});
 it('confirmação tardia após destruir não inicia escrita',async()=>{let confirmar!:(r:boolean)=>void;dialogo.confirmar.and.returnValue(new Promise<boolean>(r=>confirmar=r));const f=TestBed.createComponent(TrocasComponent);const acao=f.componentInstance.responder(pedido,true);f.destroy();confirmar(true);await acao;expect(api.responder).not.toHaveBeenCalled();});
 it('formulário envia compromisso próprio, substituto e versão',async()=>{portal.consultar.and.returnValue(of({vinculado:true,compromissos:[{id:'escala-v',tipo:'ESCALA',titulo:'Missa',inicio:pedido.inicio,termino:'2099-10-02T22:00:00',local:null,funcao:'MISSAL',vagaId:'v',resposta:'PENDENTE',versao:2,respondidoEm:null,prazoResposta:'2099-10-03T00:00:00Z'}]}));api.solicitar.and.returnValue(of(pedido));const f=TestBed.createComponent(TrocasComponent);f.detectChanges();await f.whenStable();f.componentInstance.vagaId='v';f.componentInstance.substitutoId='b';f.detectChanges();await f.whenStable();const form=f.debugElement.query(By.directive(NgForm)).injector.get(NgForm);await f.componentInstance.solicitar(form);expect(api.solicitar).toHaveBeenCalledOnceWith('v','b',2);});
 it('formulário incompleto não inicia solicitação',async()=>{const f=TestBed.createComponent(TrocasComponent);f.detectChanges();await f.whenStable();const form=f.debugElement.query(By.directive(NgForm)).injector.get(NgForm);await f.componentInstance.solicitar(form);expect(api.solicitar).not.toHaveBeenCalled();expect(form.form.touched).toBeTrue();});

});
