import {TestBed} from '@angular/core/testing';import {signal} from '@angular/core';import {of,Subject} from 'rxjs';import {CoordenacaoComponent} from './coordenacao.component';import {PastoraisApiService,Equipe,Membro} from './pastorais-api.service';import {SessaoAtual} from '../../core/layout/sessao-atual';import {DialogoService} from '../../shared/services/dialogo.service';
describe('Coordenação própria',()=>{
 let api:jasmine.SpyObj<PastoraisApiService>,dialogo:jasmine.SpyObj<DialogoService>;const e:Equipe={id:'e',nome:'Equipe',descricao:null,ativo:true,versao:0};const m:Membro={id:'m',pessoaId:'p',nome:'Participante',papel:'MEMBRO',ativo:true,versao:2};
 beforeEach(()=>{api=jasmine.createSpyObj('api',['minhasEquipes','membrosProprios','alterarProprio']);api.minhasEquipes.and.returnValue(of([e]));api.membrosProprios.and.returnValue(of({itens:[m],total:1,pagina:0,tamanho:30}));api.alterarProprio.and.returnValue(of(undefined));dialogo=jasmine.createSpyObj('dialogo',['confirmar']);dialogo.confirmar.and.resolveTo(true);TestBed.configureTestingModule({imports:[CoordenacaoComponent],providers:[{provide:PastoraisApiService,useValue:api},{provide:SessaoAtual,useValue:{permissoes:signal(['PASTORAL_COORDENACAO_GERENCIAR'])}},{provide:DialogoService,useValue:dialogo}]});});
 it('coordenador não pode alterar outro coordenador',async()=>{const f=TestBed.createComponent(CoordenacaoComponent);f.detectChanges();f.componentInstance.abrir(e);await f.componentInstance.alterar({...m,papel:'COORDENADOR'});expect(api.alterarProprio).not.toHaveBeenCalled();});
 it('trocar equipe cancela resultado antigo',()=>{const antigo=new Subject<any>();api.membrosProprios.and.returnValue(antigo);const f=TestBed.createComponent(CoordenacaoComponent);f.detectChanges();f.componentInstance.abrir(e);api.membrosProprios.and.returnValue(of({itens:[],total:0,pagina:0,tamanho:30}));f.componentInstance.abrir({...e,id:'outra'});antigo.next({itens:[m],total:1});expect(f.componentInstance.membros()).toEqual([]);});
 it('não escreve após trocar equipe durante confirmação',async()=>{let confirmar!:(v:boolean)=>void;dialogo.confirmar.and.returnValue(new Promise(r=>confirmar=r));const f=TestBed.createComponent(CoordenacaoComponent);f.detectChanges();f.componentInstance.abrir(e);const acao=f.componentInstance.alterar(m);f.componentInstance.abrir({...e,id:'outra'});confirmar(true);await acao;expect(api.alterarProprio).not.toHaveBeenCalled();});
 it('gestão envia somente membro da equipe selecionada e recarrega',async()=>{const f=TestBed.createComponent(CoordenacaoComponent);f.detectChanges();f.componentInstance.abrir(e);await f.componentInstance.alterar(m);expect(api.alterarProprio).toHaveBeenCalledOnceWith('e',m);expect(api.membrosProprios).toHaveBeenCalledTimes(2);});
});
