import { Component,ChangeDetectionStrategy,OnInit,OnDestroy,inject,signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule,NgForm } from '@angular/forms';
import { forkJoin,Subscription } from 'rxjs';
import { AniversariosApiService,ConfigAniversario,AutorizacaoAniversario } from './aniversarios-api.service';
import { SessaoAtual } from '../../core/layout/sessao-atual';
import { mensagemApi } from '../../core/api/api-error';
import { DialogoService } from '../../shared/services/dialogo.service';
import { CabecalhoPaginaComponent } from '../../shared/components/cabecalho-pagina/cabecalho-pagina.component';
import { RodapeFormComponent } from '../../shared/components/rodape-form/rodape-form.component';
@Component({selector:'app-aniversarios',imports:[CommonModule,FormsModule,CabecalhoPaginaComponent,RodapeFormComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<div class="space-y-5"><app-cabecalho-pagina titulo="Felicitações de aniversário" subtitulo="Somente pessoas que autorizaram este tipo de mensagem. Sem autorização presumida."><div acoes><button type="button" class="btn-secondary" [disabled]="ocupado()||carregando()" (click)="carregar()">Atualizar configuração</button></div></app-cabecalho-pagina>
@if(erro()){<p class="card p-4 text-red-700" role="alert">{{erro()}}</p>}@if(aviso()){<p class="card p-4 text-emerald-700" role="status">{{aviso()}}</p>}@if(carregando()){<p role="status">Consultando…</p>}
<section class="card p-5 space-y-2"><h2 class="secao-titulo">Como funciona</h2><p>Preparação a partir das 8h no horário de Brasília, na data do aniversário. Nascidos em 29/02 são lembrados em 28/02 nos anos não bissextos. A fila aplica cotas e as regras do canal. Uma mensagem por pessoa, canal e ano.</p><p>Autorizar WhatsApp no cadastro geral não autoriza felicitações. Registre a autorização específica abaixo e sua origem. Revogar impede nova reserva; uma mensagem já enviada ou em envio pode não ser recuperável.</p><p>As mensagens usam layouts revisados pela equipe. Configure um assunto no layout de e-mail. Não há mensagem criada automaticamente.</p></section>
@for(c of configs();track c.canal){<form #form="ngForm" (ngSubmit)="salvarConfig(c,form)"><section class="card p-5 space-y-3"><h2 class="secao-titulo">{{c.canal==='EMAIL'?'E-mail':'WhatsApp'}}</h2><span class="badge" [class]="c.agendadorAtivo?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'">{{c.agendadorAtivo?'Agendador habilitado no ambiente':'Agendador desligado no ambiente'}}</span><fieldset [disabled]="ocupado()||!pode('ANIVERSARIO_CONFIGURAR')" class="space-y-3"><label class="label"><input type="checkbox" name="ativo" [(ngModel)]="c.ativo"> Habilitar felicitações deste canal</label><label class="label" [for]="'layout-'+c.canal">Layout revisado</label><select [id]="'layout-'+c.canal" class="field w-full" name="layout" [required]="c.ativo" [(ngModel)]="c.layoutId"><option [ngValue]="null">Escolha um layout</option>@for(l of layouts();track l.id){@if(l.canal===c.canal){<option [ngValue]="l.id">{{l.nome}}</option>}}</select></fieldset></section>@if(pode('ANIVERSARIO_CONFIGURAR')){<app-rodape-form [carregando]="ocupado()" (cancelar)="carregar()"/>}</form>}
@if(pode('PESSOA')){<section class="card p-5 space-y-3"><h2 class="secao-titulo">Autorizações por pessoa</h2><label class="label" for="busca-aniversario">Buscar pessoa pelo nome</label><div class="flex gap-2"><input id="busca-aniversario" class="field" maxlength="160" [(ngModel)]="busca"><button type="button" class="btn-secondary" [disabled]="ocupado()||carregandoPessoa()" (click)="buscarPessoas()">Buscar</button></div><label class="label" for="pessoa-aniversario">Pessoa</label><select id="pessoa-aniversario" class="field w-full" [ngModel]="pessoaId" [disabled]="ocupado()" (ngModelChange)="selecionarPessoa($event)"><option value="">Selecione</option>@for(p of pessoas();track p.id){<option [value]="p.id">{{p.nomeCompleto}}</option>}</select><p class="text-sm text-slate-500">Até 30 pessoas por busca. Apenas nome e identificador são usados na seleção.</p>@if(carregandoPessoa()){<p role="status">Consultando autorizações…</p>}</section>
@for(a of autorizacoes();track a.canal){<form #form="ngForm" (ngSubmit)="salvarAutorizacao(a,form)"><section class="card p-5 space-y-3"><h2 class="secao-titulo">Autorização de {{a.canal==='EMAIL'?'e-mail':'WhatsApp'}}</h2><fieldset [disabled]="ocupado()||carregandoPessoa()||!pode('ANIVERSARIO_AUTORIZAR')" class="space-y-3"><label class="label"><input type="checkbox" name="autorizado" [(ngModel)]="a.autorizado"> Confirmo que esta pessoa autorizou receber felicitações neste canal</label><label class="label" [for]="'fonte-'+a.canal">Origem da autorização ou motivo da revogação</label><input [id]="'fonte-'+a.canal" class="field w-full" name="fonte" required maxlength="200" [(ngModel)]="a.fonte"><p class="text-sm text-slate-500">Registre uma referência breve; não inclua documentos nem dados sensíveis.</p></fieldset>@if(a.registradoEm){<p>Último registro: {{a.registradoEm|date:'dd/MM/yyyy HH:mm'}}</p>}</section>@if(pode('ANIVERSARIO_AUTORIZAR')){<app-rodape-form [carregando]="ocupado()" (cancelar)="selecionarPessoa(pessoaId)"/>}</form>}}
</div>`})
export class AniversariosComponent implements OnInit,OnDestroy{
 private readonly api=inject(AniversariosApiService);private readonly sessao=inject(SessaoAtual);private readonly dialogo=inject(DialogoService);private carga?:Subscription;private pessoaCarga?:Subscription;private buscaCarga?:Subscription;private escrita?:Subscription;private destruido=false;
 readonly configs=signal<ConfigAniversario[]>([]);readonly layouts=signal<{id:string;nome:string;canal:string}[]>([]);readonly pessoas=signal<{id:string;nomeCompleto:string}[]>([]);readonly autorizacoes=signal<AutorizacaoAniversario[]>([]);readonly erro=signal('');readonly aviso=signal('');readonly carregando=signal(false);readonly carregandoPessoa=signal(false);readonly ocupado=signal(false);busca='';pessoaId='';
 ngOnInit(){this.carregar();}pode(c:string){return this.sessao.permissoes().includes(c);}
 carregar(){if(this.ocupado()||this.destruido)return;this.carga?.unsubscribe();this.configs.set([]);this.erro.set('');this.carregando.set(true);this.carga=forkJoin({configs:this.api.configuracoes(),layouts:this.api.layouts()}).subscribe({next:r=>{this.configs.set(r.configs.map(c=>({...c})));this.layouts.set(r.layouts);this.carregando.set(false);},error:e=>{this.carregando.set(false);this.erro.set(mensagemApi(e,'Configuração indisponível.'));}});}
 buscarPessoas(){if(this.ocupado()||!this.pode('PESSOA'))return;this.buscaCarga?.unsubscribe();this.buscaCarga=this.api.pessoas(this.busca).subscribe({next:r=>this.pessoas.set(r),error:e=>{this.pessoas.set([]);this.erro.set(mensagemApi(e,'Busca indisponível.'));}});}
 selecionarPessoa(id:string){if(this.ocupado()||this.destruido)return;this.pessoaCarga?.unsubscribe();this.pessoaId=id;this.autorizacoes.set([]);this.carregandoPessoa.set(false);if(!id)return;this.carregandoPessoa.set(true);this.pessoaCarga=this.api.autorizacoes(id).subscribe({next:r=>{this.autorizacoes.set(r.map(a=>({...a})));this.carregandoPessoa.set(false);},error:e=>{this.carregandoPessoa.set(false);this.erro.set(mensagemApi(e,'Autorizações indisponíveis.'));}});}
 salvarConfig(c:ConfigAniversario,f:NgForm){if(this.ocupado()||this.carregando()||!this.pode('ANIVERSARIO_CONFIGURAR'))return;if(f.invalid){f.control.markAllAsTouched();return;}this.ocupado.set(true);this.erro.set('');this.escrita=this.api.configurar({...c}).subscribe({next:r=>{this.configs.update(v=>v.map(x=>x.canal===r.canal?r:x));this.ocupado.set(false);this.aviso.set('Configuração salva.');},error:e=>{this.ocupado.set(false);this.erro.set(mensagemApi(e,'Não foi possível salvar. Atualize antes de tentar novamente.'));}});}
 async salvarAutorizacao(a:AutorizacaoAniversario,f:NgForm){if(this.ocupado()||this.carregandoPessoa()||a.pessoaId!==this.pessoaId||!this.pode('ANIVERSARIO_AUTORIZAR'))return;if(f.invalid){f.control.markAllAsTouched();return;}const req={...a};this.ocupado.set(true);try{if(!await this.dialogo.confirmar({mensagem:req.autorizado?'Registrar a autorização específica para felicitações neste canal?':'Revogar a autorização para felicitações neste canal?',confirmar:req.autorizado?'Registrar autorização':'Revogar'})||this.destruido){this.ocupado.set(false);return;}this.escrita=this.api.autorizar(req).subscribe({next:r=>{this.autorizacoes.update(v=>v.map(x=>x.canal===r.canal?r:x));this.ocupado.set(false);this.aviso.set('Autorização registrada.');},error:e=>{this.ocupado.set(false);this.erro.set(mensagemApi(e,'Não foi possível registrar. Atualize as autorizações.'));}});}catch{this.ocupado.set(false);this.erro.set('Não foi possível registrar.');}}
 ngOnDestroy(){this.destruido=true;this.carga?.unsubscribe();this.pessoaCarga?.unsubscribe();this.buscaCarga?.unsubscribe();this.escrita?.unsubscribe();}
}
