import {TestBed} from '@angular/core/testing';import {signal} from '@angular/core';import {of,Subject,throwError} from 'rxjs';import {NgForm} from '@angular/forms';
import {AniversariosComponent} from './aniversarios.component';import {AniversariosApiService,AutorizacaoAniversario} from './aniversarios-api.service';import {SessaoAtual} from '../../core/layout/sessao-atual';import {DialogoService} from '../../shared/services/dialogo.service';
describe('Aniversários: autorização explícita',()=>{
 let api:jasmine.SpyObj<AniversariosApiService>,dialogo:jasmine.SpyObj<DialogoService>;const perms=signal(['ANIVERSARIO_CONFIGURAR','ANIVERSARIO_AUTORIZAR','PESSOA']);const a:AutorizacaoAniversario={pessoaId:'p',canal:'EMAIL',autorizado:false,fonte:'Pedido da pessoa',versao:2,registradoEm:null};const form={invalid:false} as NgForm;
 beforeEach(()=>{api=jasmine.createSpyObj('aniv',['configuracoes','layouts','configurar','pessoas','autorizacoes','autorizar']);api.configuracoes.and.returnValue(of([{canal:'EMAIL',ativo:false,layoutId:null,versao:0,agendadorAtivo:false}]));api.layouts.and.returnValue(of([]));api.autorizacoes.and.returnValue(of([a]));api.autorizar.and.callFake(req=>of(req));dialogo=jasmine.createSpyObj('dialogo',['confirmar']);dialogo.confirmar.and.resolveTo(true);perms.set(['ANIVERSARIO_CONFIGURAR','ANIVERSARIO_AUTORIZAR','PESSOA']);TestBed.configureTestingModule({imports:[AniversariosComponent],providers:[{provide:AniversariosApiService,useValue:api},{provide:SessaoAtual,useValue:{permissoes:perms}},{provide:DialogoService,useValue:dialogo}]});});
 it('informa agendador desligado e não presume consentimento',()=>{const f=TestBed.createComponent(AniversariosComponent);f.detectChanges();f.componentInstance.selecionarPessoa('p');f.detectChanges();expect(f.nativeElement.textContent).toContain('Agendador desligado');expect(f.componentInstance.autorizacoes()[0].autorizado).toBeFalse();expect(api.autorizar).not.toHaveBeenCalled();});
 it('revogação exige confirmação e mantém versão',async()=>{const f=TestBed.createComponent(AniversariosComponent);f.detectChanges();f.componentInstance.selecionarPessoa('p');await f.componentInstance.salvarAutorizacao({...a},form);expect(dialogo.confirmar).toHaveBeenCalledWith(jasmine.objectContaining({confirmar:'Revogar'}));expect(api.autorizar).toHaveBeenCalledWith(jasmine.objectContaining({autorizado:false,versao:2,pessoaId:'p'}));});
 it('cancelar confirmação não altera autorização',async()=>{dialogo.confirmar.and.resolveTo(false);const f=TestBed.createComponent(AniversariosComponent);f.detectChanges();f.componentInstance.selecionarPessoa('p');await f.componentInstance.salvarAutorizacao(a,form);expect(api.autorizar).not.toHaveBeenCalled();});
 it('leitor não modifica autorizações',async()=>{perms.set(['PESSOA']);const f=TestBed.createComponent(AniversariosComponent);f.detectChanges();f.componentInstance.selecionarPessoa('p');await f.componentInstance.salvarAutorizacao(a,form);expect(api.autorizar).not.toHaveBeenCalled();});
 it('mudança de pessoa cancela resposta anterior',()=>{const antiga=new Subject<AutorizacaoAniversario[]>();api.autorizacoes.and.returnValue(antiga);const f=TestBed.createComponent(AniversariosComponent);f.detectChanges();f.componentInstance.selecionarPessoa('p');api.autorizacoes.and.returnValue(of([]));f.componentInstance.selecionarPessoa('outra');antiga.next([a]);expect(f.componentInstance.autorizacoes()).toEqual([]);expect(antiga.observed).toBeFalse();});
 it('falha de configuração não exibe controles com valores antigos',()=>{api.configuracoes.and.returnValue(throwError(()=>new Error('falha')));const f=TestBed.createComponent(AniversariosComponent);f.detectChanges();expect(f.componentInstance.configs()).toEqual([]);expect(f.componentInstance.erro()).toBeTruthy();});
});
