import { TestBed } from '@angular/core/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { signal } from '@angular/core';
import { of, Subject } from 'rxjs';
import { OrganizacaoComponent } from './organizacao.component';
import { OrganizacaoApiService, PaginaOrganizacao } from './organizacao-api.service';
import { SessaoAtual } from '../../core/layout/sessao-atual';
import { FuncionalidadesPlanoService } from '../../core/plano/funcionalidades-plano.service';
describe('Mural e tarefas',()=>{
 let api:jasmine.SpyObj<OrganizacaoApiService>;let permissoes:ReturnType<typeof signal<string[]>>;let plano:jasmine.SpyObj<FuncionalidadesPlanoService>;
 const registro={id:'a',titulo:'Aviso',descricao:'<script>alert(1)</script>',status:'PUBLICADO',prazo:null,versao:3,criadoEm:'2026-10-01T00:00:00Z',atualizadoEm:'2026-10-01T00:00:00Z'};
 beforeEach(()=>{api=jasmine.createSpyObj('api',['listar','salvar']);api.listar.and.returnValue(of({itens:[registro],total:1,pagina:0,tamanho:30}));api.salvar.and.returnValue(of(registro));permissoes=signal(['MURAL','MURAL_CRIAR','MURAL_ALTERAR']);plano=jasmine.createSpyObj('plano',['consultar']);plano.consultar.and.returnValue(of(['MURAL','TAREFAS']));TestBed.configureTestingModule({imports:[OrganizacaoComponent],providers:[provideRouter([]),{provide:ActivatedRoute,useValue:{snapshot:{data:{modulo:'mural'}}}},{provide:OrganizacaoApiService,useValue:api},{provide:SessaoAtual,useValue:{permissoes}},{provide:FuncionalidadesPlanoService,useValue:plano}]});});
 it('consulta paginada e detalhes tratam texto como texto',async()=>{const f=TestBed.createComponent(OrganizacaoComponent);f.detectChanges();expect(api.listar).toHaveBeenCalledWith('mural','','',0);f.componentInstance.abrir(registro);f.detectChanges();await f.whenStable();f.detectChanges();expect(f.nativeElement.querySelector('script')).toBeNull();expect(f.nativeElement.querySelector('textarea').value).toContain('<script>');});
 it('mantém versão ao editar e não envia equipe no mural',()=>{const f=TestBed.createComponent(OrganizacaoComponent);f.detectChanges();f.componentInstance.abrir(registro);f.detectChanges();f.nativeElement.querySelector('form').dispatchEvent(new Event('submit'));expect(api.salvar).toHaveBeenCalledWith('mural','a',jasmine.objectContaining({versao:3}));expect(api.salvar.calls.mostRecent().args[2].equipe).toBeUndefined();});
 it('oculta criação e impede salvamento sem permissão',()=>{permissoes.set(['MURAL']);const f=TestBed.createComponent(OrganizacaoComponent);f.detectChanges();expect(f.nativeElement.textContent).not.toContain('Novo registro');f.componentInstance.novo();f.detectChanges();f.nativeElement.querySelector('form').dispatchEvent(new Event('submit'));expect(api.salvar).not.toHaveBeenCalled();});
 it('sem funcionalidade mantém leitura e bloqueia escrita',()=>{plano.consultar.and.returnValue(of([]));const f=TestBed.createComponent(OrganizacaoComponent);f.detectChanges();expect(f.componentInstance.itens().length).toBe(1);f.componentInstance.novo();f.detectChanges();f.nativeElement.querySelector('form').dispatchEvent(new Event('submit'));expect(api.salvar).not.toHaveBeenCalled();});
 it('cancelamento da busca antiga impede resultados obsoletos',()=>{const antiga=new Subject<PaginaOrganizacao>();api.listar.and.returnValue(antiga);const f=TestBed.createComponent(OrganizacaoComponent);f.detectChanges();api.listar.and.returnValue(of({itens:[],total:0,pagina:0,tamanho:30}));f.componentInstance.buscar();antiga.next({itens:[registro],total:1,pagina:0,tamanho:30});expect(f.componentInstance.total()).toBe(0);f.destroy();});
 it('tarefa tem estados e equipe próprios',()=>{TestBed.overrideProvider(ActivatedRoute,{useValue:{snapshot:{data:{modulo:'tarefas'}}}});permissoes.set(['TAREFA','TAREFA_CRIAR']);const f=TestBed.createComponent(OrganizacaoComponent);f.detectChanges();f.componentInstance.novo();f.detectChanges();expect(f.componentInstance.estados).toContain('CONCLUIDA');expect(f.nativeElement.querySelector('#org-equipe')).toBeTruthy();expect(api.listar).toHaveBeenCalledWith('tarefas','','',0);});
});
